export interface RoomCreateRequest {
  type: "create_room";
  data: "";
  id: 0;
}

export interface RoomAddUserRequest {
  type: "add_user_to_room";
  data: {
    indexRoom: number | string;
  };
  id: number;
}

export interface RoomCreateGameResponse {
  type: "create_game"; //send for both players in the room, after they are connected to the room
  data: {
    idGame: number | string;
    idPlayer:
      | number
      | string /* generated by server id for player in the game session, not enemy (unique id for every player) */;
  };
  id: number;
}

export interface RoomUpdateStateResponse {
  type: "update_room";
  data: [
    {
      roomId: number | string;
      roomUsers: [
        {
          name: string;
          index: number | string;
        },
      ];
    },
  ];
  id: number;
}
